#!/bin/bash
cd output7

echo "Counting Observations"
ls | xargs egrep -c "Observation" > ../tmp/observations
echo "Counting Dimensions"
ls | xargs egrep -c "DimensionProperty|TimeComponentSpecification|YearComponentSpecification" > ../tmp/dimensions 
echo "Counting Attributes"
ls | xargs egrep -c "AttributeProperty|CountryComponentSpecification|CurrencyComponentSpecification" > ../tmp/attributes 
echo "Counting Measures"
ls | xargs egrep -c "MeasureProperty" > ../tmp/measures
echo "Counting Triples"
ls | xargs wc -l > ../tmp/triples

cd ../tmp
for file in observations dimensions attributes measures triples
do
 echo "Sorting $file"
 sort $file -o $file  -n -k 2 -t ":"
 grep -o "[0-9]*$" $file > "$file"_numbersonly
done
for file in dimensions attributes measures
do
 echo "Creating Histogram for $file"
 uniq -c "$file"_numbersonly > "$file"_histogram
done
cd ..
